server:
  port: 8081
spring:
  datasource:
        driverClassName:  com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/java1908?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
  jpa:
    database: mysql
